siteTitle="Daniel Hollcraft"
profileHeading= "Full Stack Javascript Developer"
linkedinProfile= "https://www.linkedin.com/in/daniel-hollcraft-752509b/"
githubProfile= "https://github.com/danielbh"
googleAnalyticsId = "UA-40454074-3"
