service: danielhollcraft

frameworkVersion: ">=1.8.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SLS_STAGE: ${self:custom.stage}
    SUBJECT: 'danielhollcraft.com contact form'
    FROM: ${file(./secret.yaml):FROM}
    TO: ${file(./secret.yaml):TO}
    API_KEY: ${file(./secret.yaml):API_KEY}
    DOMAIN: mg.danielhollcraft.com

functions:
  contact:
    handler: index.handler
    events:
      - http:
          path: /contact
          method: post
          cors: true

plugins:
  - serverless-offline

resources:
  Resources:
    CustomDomainMap:
      Type: "AWS::ApiGateway::BasePathMapping"
      Properties:
        DomainName: api.danielhollcraft.com
        Stage: ${self:custom.stage}
        RestApiId: {Ref: ApiGatewayRestApi}